-- FANWEB INDUSTRIAL / Supabase PostgreSQL schema
-- Run this once in Supabase SQL Editor before the first Vercel deployment.

create table if not exists public.fanweb_admin (
  id bigint generated by default as identity primary key,
  username varchar(80) not null unique,
  password_hash varchar(255) not null,
  created_at timestamptz not null default now()
);

create table if not exists public.fanweb_product (
  id bigint generated by default as identity primary key,
  sku varchar(80) not null unique,
  name varchar(200) not null,
  slug varchar(220) not null unique,
  category varchar(120) not null default 'Quạt ly tâm',
  short_description varchar(500) not null default '',
  description text not null default '',
  airflow varchar(120) not null default '',
  pressure varchar(120) not null default '',
  motor varchar(120) not null default '',
  voltage varchar(120) not null default '',
  speed varchar(120) not null default '',
  image_url varchar(500) not null default '',
  featured boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.fanweb_inquiry (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  phone varchar(50) not null,
  email varchar(160) not null default '',
  product varchar(200) not null default '',
  message text not null default '',
  status varchar(30) not null default 'new',
  created_at timestamptz not null default now()
);

create index if not exists idx_product_active_featured on public.fanweb_product (active, featured);
create index if not exists idx_product_category on public.fanweb_product (category);
create index if not exists idx_inquiry_status_created on public.fanweb_inquiry (status, created_at desc);

create table if not exists public.fanweb_product_image (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.fanweb_product(id) on delete cascade,
  image_url varchar(700) not null,
  sort_order integer not null default 0,
  is_cover boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_fanweb_product_image_product on public.fanweb_product_image (product_id, sort_order);

-- The Flask server connects with a privileged Postgres credential. RLS protects these
-- public-schema tables from accidental browser/Data API exposure.
alter table public.fanweb_admin enable row level security;
alter table public.fanweb_product enable row level security;
alter table public.fanweb_inquiry enable row level security;

-- Product image bucket. The application uses the server-side service-role key
-- to upload images, so storage access is kept out of the browser.
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

-- Public read access for product images. Upload/update/delete are performed
-- server-side with the service-role key.
do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'product-images-public-read'
  ) then
    create policy "product-images-public-read"
    on storage.objects for select
    to public
    using (bucket_id = 'product-images');
  end if;
end
$$;

-- Keep Data API disabled for these tables by default; this Flask app connects
-- to Postgres with the server-side DATABASE_URL.
